### ISSUE TITLE
merge per-chromosome chains

### ISSUE THREAD

**Issue by rapamycin** [hillerlab/GenomeAlignmentTools#10]
Dear all,

I followed your pipelines that published in gagascience (2020, 120way mammal) and aligned a new rodent genome to hg38 using LASTZ.
Considering the computational resources required, I splited hg38 genome to hundreds chunks according to chromosome/scaffold name and did the LASTZ & axtChain.
After axtChain, some other pipelines suggest to merge all splited chains into one large chain before chainPreNet(e.g. http://genomewiki.ucsc.edu/index.php/Whole_genome_alignment_howto).

So, in your pipeline, do we need to merge all per-chromosome chains before RepeatFiller? If YES, could you please simply explain why? If NO, which step do I need to merge per-chromosome files? OR, I can follow your pipeline using split-run style all the time?

Best Wishes!

Tao

**Comment by MichaelHiller** [comment]
Hi Tao, 
my understanding of chainPreNet is that this removes small low-scoring chains will are likely 'netted away' because they represent non-homologous repeats. This just cleans up the data a bit and makes netting run faster. 

Since RepeatFiller works at the level of the chains, chainPreNet can be run after RepeatFiller. Meaning feed all chains to RepeatFiller. 
I assume that first running chainPreNet and then RepeatFiller gives very similar results, but I haven't tested that. 

You can run RepeatFiller in parallel on your split chain chunks. 

Michael

**Comment by MichaelHiller** [comment]
No, when running chainCleaner (which considers all chains at once) and chainNet + downstream steps (which also consider all chains to get nets), you CANNOT split the chains. You must provide all in one file, ideally after score-sorting with chainSort.

**Comment by rapamycin** [comment]
Thank you so much, that make sense!
